### ISSUE TITLE
Commulative vs commutative

### ISSUE THREAD

**Issue by davidavdav** [idiap/FiniteStateTransducers.jl#5]
Hello, 

Thanks for this package, I use it for building a decoder for ASR. 

In [semirings.jl](https://github.com/idiap/FiniteStateTransducers.jl/blob/430bf273960bd3f43f4042ee85a7c9f3d846d37f/src/semirings/semirings.jl#L68) you define `iscommulative`, which apparently means that multiplication is commutative.   I didn't know the word, searching for it doesn't give much information.  It may be semiring jargon, but since a semiring's addition is commutative by definition, would it not be better to call the function `iscommutative`?

**Comment by nantonel** [comment]
Hey, yes that is probably I typo, sorry about that. Feel free to create a PR to fix that. Sorry the package is currently not under development (I'm not in Idiap anymore) but in case you're interested in further developing it let me know!

**Comment by davidavdav** [comment]
Ah great, sure I'll do so.  I might have a few more things for other PRs, regarding i/o and the like.  One thing I might be interested in to make is a fallback to openfst for all the un-checked boxes in #1, e.g. through a complicated subprocess or by PyCalls to pywrapfst (a very un-pythonic wrapper around openfst).
